# Step 1: Build stage
FROM node:18.8.0-alpine3.16 As build-stage

WORKDIR /usr/app

COPY package*.json ./

RUN yarn install

COPY . .

RUN yarn build

# Step 1: Production stage
FROM nginx:1.12-alpine As production-stage

WORKDIR /usr/share/nginx/html

RUN rm -rf ./*

COPY --from=build-stage /usr/app/build .

EXPOSE 80

ENTRYPOINT [ "nginx","-g","daemon off;" ]