### Signup a new user
POST http://localhost:3000/users/signup
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"test"
}


### Signin with email and password
POST http://localhost:3000/users/signin
Content-Type: application/json

{
    "email":"test@test.com",
    "password":"test"
}


### Signout user
POST http://localhost:3000/users/signout