### Create a new user
POST http://localhost:3001/users/create
Content-Type: application/json

{
    "email":"parastar.2mehdi@gmail.com",
    "password":"mehdi"
}



### Login with email and password

# @name login

POST http://localhost:3001/users/login
Content-Type: application/json

{
    "email":"parastar.mehdi@gmail.com",
    "password":"mehdi"
}



### Get Current User

@access_token = {{login.response.body.access_token}}

GET  http://localhost:3001/users/profile
Content-Type: application/json
Authorization: Bearer {{access_token}}

### Signin with email and password
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"aaa@aaa.com",
    "password":"mehdi"
}



### Signout user
POST http://localhost:3000/auth/signout


### Approve an existing report
PATCH http://localhost:3000/auth/change-user-roles/2
Content-Type: application/json

{
    "admin":true
}


### Get the currently signed in user
GET http://localhost:3000/auth/whoami


### Change user email
PATCH http://localhost:3000/auth/change-email
Content-Type: application/json

{
    "email":"aaa@aaa.com"
}


### Change user password
PATCH http://localhost:3000/auth/change-password
Content-Type: application/json

{
    "password":"mehdi"
}


### Delete a particular user with a given id 
DELETE  http://localhost:3000/auth/delete-user/2


### Get a particular user with a given id 
Get  http://localhost:3000/auth/find-by-id?id=1


### Get a particular user with a given email 
GET   http://localhost:3000/auth/find-by-email?email=aaa@aaa.com