### Signup a new user
POST http://localhost:3000/auth/signup
Content-Type: application/json

{
    "email":"test02@test.com",
    "password":"test"
}


### Signin with email and password
POST http://localhost:3000/auth/signin
Content-Type: application/json

{
    "email":"aaa@aaa.com",
    "password":"mehdi"
}


### Signout user
POST http://localhost:3000/auth/signout


### Approve an existing report
PATCH http://localhost:3000/auth/change-user-roles/2
Content-Type: application/json

{
    "admin":true
}


### Get the currently signed in user
GET http://localhost:3000/auth/whoami


### Change user email
PATCH http://localhost:3000/auth/change-email
Content-Type: application/json

{
    "email":"aaa@aaa.com"
}


### Change user password
PATCH http://localhost:3000/auth/change-password
Content-Type: application/json

{
    "password":"mehdi"
}


### Delete a particular user with a given id 
DELETE  http://localhost:3000/auth/2


### Get a particular user with a given id 
Get  http://localhost:3000/auth/find-by-id?id=1


### Get a particular user with a given email 
GET   http://localhost:3000/auth/find-by-email?email=aaa@aaa.com