
FROM node:18.8.0-alpine3.16 AS development

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install glob rimraf

RUN apk update
RUN apk add
RUN apk add ffmpeg

RUN apk add --no-cache git make cmake gcc g++ libmad-dev \
    libid3tag-dev libsndfile-dev gd-dev boost-dev \
    libgd libpng-dev zlib-dev && \
    apk add --no-cache zlib-static libpng-static boost-static && \
    apk add --no-cache autoconf automake libtool gettext && \
    wget https://github.com/xiph/flac/archive/1.3.3.tar.gz && \
    tar xzf 1.3.3.tar.gz && \
    cd flac-1.3.3 && \
    ./autogen.sh && \
    ./configure --enable-shared=no && \
    make && \
    make install

RUN npm install --only=development

COPY . .

ENV NODE_ENV development

RUN npm run build